generator:
  class: sfPropelGenerator
  param:
    model_class:           EdaPersonas
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              EdaPersonas
    plural:                EdaPersonass
    route_prefix:          eda_personas
    with_propel_route:     1
    actions_base_class:    sfActions
    css:                   none

    config:
      actions:
        _new:    { credentials: [EDAGESTIONPLUGIN_administracion] }
      fields:
        apellido1: { label: Apellido 1º }
        apellido2: { label: Apellido 2º }
        docidentificacion: { label: Documento }
        id_tipodocidentificacion: {label: Tipo Documento }
        id_paisdocidentificacion: {label: País del Documento }
        sfusername: { label: Username }       
      list:
        title: Listado de Personas
        display: [ =nombre, apellido1, apellido2, sfusername, docidentificacion]
        max_per_page: 10
        object_actions:
          _edit: ~
          _delete: ~
          asociaPerfiles: { label: perfiles }
          cambiaPassword: { label: password }
         
      filter:
        display: [ nombre, apellido1, apellido2, docidentificacion, sexo, fechanacimiento]
      form:
        class: EdaPersonasConTelEmailDirForm
        display:
          'NONE':           [nombre, apellido1, apellido2, id_tipodocidentificacion, docidentificacion, sexo, fechanacimiento, observaciones,created_at, updated_at, profesion ]
          'identificación': [identificacion]
          'teléfonos':     [telefono*]
          'e-mails':        [email*]
          'direcciones':    [direccion*]
      edit:
        title: Edición de la persona: %%NOMBRE%% %%APELLIDO1%% %%APELLIDO2%%
      new:
        title: Nueva Persona
