login_papi:
  url: /login_papi
  param: { module: sftPAPISesion, action: index }

papi_signin:
  url: /papi_signin
  param: { module: sftPAPIAS, action: signin }
  
sftPAPIPlugin_poaParams:
  url: /poaParams
  param: { module: sftPAPIAdmin, action: poaParams }