generator:
  class: sfPropelGenerator
  param:
    model_class:           GenLocalidad
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              GenLocalidad
    plural:                GenLocalidads
    route_prefix:          gen_localidad
    with_propel_route:     1
    actions_base_class:    sfActions
    css:                   false

    config:
      actions: ~
      fields:  
        GenProvincia: { label: provincia }
      list:
        title: Listado de Localidades
        max_per_page: 10
        display: [ nombre, GenProvincia ]
      filter:  ~
      form:    ~
      edit:
        title: Edicion de la Localidad: %%NOMBRE%%
      new:
        title: Nueva Localidad

