generator:
  class: sfPropelGenerator
  param:
    model_class:           EdaTiposDocidentificacion
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              EdaTiposDocidentificacion
    plural:                EdaTiposDocidentificacions
    route_prefix:          eda_tipos_docidentificacion
    with_propel_route:     1
    actions_base_class:    sfActions
    css:                   none

    config:
      actions: ~
      fields:
        funciondecontrol: [ label: funciondecontrol ]
      list:
        title: Listado de tipos de documentos de identificaci贸n
        display: [ nombre, funciondecontrol ]
        max_per_page: 10
      filter:  ~
      form:    ~
      edit:
        title: Edici贸n del tipo de documento de identificaci贸n: %%NOMBRE%%
      new:
        title: Nuevo tipo de documento de indentificaci贸n
