generator:
  class: sfPropelGenerator
  param:
    model_class:           SftOrganismo
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              SftOrganismo
    plural:                SftOrganismos
    route_prefix:          sft_organismo
    with_propel_route:     1
    actions_base_class:    sfActions
    css:                   none

    config:
      actions:
        _new:    { credentials: [SFTGESTIONPLUGIN_administracion] }
      fields:
        docidentificacion: { label: Documento }
        id_tipodocidentificacion: {label: Tipo Documento }
        id_paisdocidentificacion: {label: País del Documento }
        sfusername: { label: Username }
        sitioweb: {label: Sitio Web}
        descripcion: {label: Descripción}
        id_pais: {label: Id país}
        id_depende: {label: Dependencia de otro organismo}
        id_tipoorganismo: {label: Tipo de organismo}
        codigo: {label: Código}
      list:
        title: Listado de Organismos
        display: [ =nombre, abreviatura, sfusername, sitioweb]
        max_per_page: 10
        object_actions:
          _edit: ~
          _delete: ~
          asociaPerfiles: { label: perfiles }

      filter:
        display: [ nombre, abreviatura, sitioweb]
      form:
        class: SftOrganismoConIdentEmailForm
      edit:
        title: 'Edición del Organismo: %%NOMBRE%% (%%ABREVIATURA%%)'
        fields:
          nombre: {label: Nombre*, help: 'Nombre oficial del organismo'}
          email: {label: Email*, help: 'Dirección de correo de contacto con el organismo'}
      new:
        title: Nuevo Organismo
        fields:
          nombre: {label: Nombre*, help: 'Nombre oficial del organismo'}
          email: {label: Email*, help: 'Dirección de correo de contacto con el organismo'}
          
