generator:
  class: sfPropelGenerator
  param:
    model_class:           EdaTiposTelefono
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              EdaTiposTelefono
    plural:                EdaTiposTelefonos
    route_prefix:          eda_tipos_telefono
    with_propel_route:     1
    actions_base_class:    sfActions
    css:                   none

    config:
      actions: ~
      fields: ~
      list:
        title: Listado de Tipos de Teléfonos
        max_per_page: 10
        display: [ nombre ]
      filter:  ~
      form:    ~
      edit:
        title: Edición del Tipo de Teléfonos: %%NOMBRE%%
      new:
        title: Nuevo Tipo de Teléfono
