generator:
  class: sfPropelGenerator
  param:
    model_class:           EdaUsuAtributos
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              EdaUsuAtributos
    plural:                EdaUsuAtributoss
    route_prefix:          eda_usu_atributos
    with_propel_route:     1
    actions_base_class:    sfActions
    css:                   none

    config:
      actions: ~
      fields:
        nombre: { label: Nombre}
        descripcion: { label : Descripción}
      list:
        title: Listado de Atributos
        max_per_page: 10
        display: [ nombre, descripcion ]
      filter:
        display: [ nombre, descripcion ]
      form: ~
        
      edit:
        title: Edición del Atributo %%NOMBRE%%
      new:
        title: Nuevo Atributo
