generator:
  class: sfPropelGenerator
  param:
    model_class:           EdaAplicaciones
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              EdaAplicaciones
    plural:                EdaAplicacioness
    route_prefix:          eda_aplicaciones
    with_propel_route:     1
    actions_base_class:    sfActions
    css:                   none

    config:
      actions: ~
      fields:  ~
      list:
        title: Listado de Aplicaciones
        max_per_page: 10
        display: [ logotipo, nombre, url, clave]
      filter:
        display: [ nombre, url, url_svn, clave]
      form:    ~
      edit:
        title: Edición de la Aplicación: %%NOMBRE%%
      new:
        title: Nueva Aplicación