<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../../../../plugins/sftGuardPlugin/lib/form/EmbedI18n.class.php';

/**
 * Test class for EmbedI18n.
 * Generated by PHPUnit on 2011-03-11 at 12:37:39.
 */
class EmbedI18nTest extends PHPUnit_Framework_TestCase {

    /**
     * @var EmbedI18n
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new EmbedI18n;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testAniadeTraducciones().
     */
    public function testAniadeTraducciones() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
