generator:
  class: sfPropelGenerator
  param:
    model_class:           SftAmbito
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              SftAmbito
    plural:                SftAmbitos
    route_prefix:          sft_ambito
    with_propel_route:     1
    actions_base_class:    sfActions
    css:                   false

    config:
      actions: ~
      fields:
        id_periodo: { label: Periodos }
        SftPeriodo: { label: Periodos }
        id_ambitotipo: { label: Tipo de Ámbito}
        codigo: { label: Código }
        descripcion: { label: Descripción }
      list:
        title: Listado de Ámbitos
        max_per_page: 10
        display: [ nombre, descripcion, SftPeriodo, estado ]         
      filter:  ~
      form:    ~
      edit:
        title: Edición del Ámbito <i>%%NOMBRE%%</i>  del tipo de ámbito <i>%%SFTAMBITOTIPO%%</i>
        fields:
          codigo: { label: Código*, help: 'Nombre corto del ámbito, va en minúsculas y sin espacios ni simbolos extraños y se suele utilizar para identificarlo' }
        title: Nuevo Ámbito para el tipo <i>%%SFTAMBITOTIPO%%</i>
        fields:
          codigo: { label: Código*, help: 'Nombre corto del ámbito, va en minúsculas y sin espacios ni simbolos extraños y se suele utilizar para identificarlo' }
