generator:
  class: sfPropelGenerator
  param:
    model_class:           GenComunidad
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              GenComunidad
    plural:                GenComunidads
    route_prefix:          gen_comunidad
    with_propel_route:     1
    actions_base_class:    sfActions
    css:                   none

    config:
      actions: ~
      fields:  ~
      list:
        title: Listado de Comunidades
        max_per_page: 10
        display: [ nombre, nombreabrev]
      filter:  ~
      form:    ~
      edit:
        title: Edición de la Comunidad: %%NOMBRE%%
      new:
        title: Nueva Comunidad
