generator:
  class: sfPropelGenerator
  param:
    model_class:           GenComunidad
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              GenComunidad
    plural:                GenComunidads
    route_prefix:          gen_comunidad
    with_propel_route:     1
    actions_base_class:    sfActions
    css:                   none

    config:
      actions: ~
      fields:
        codigocomunidad: {label: Código}
        nombreabrev: {label: Nombre abreviado}
      list:
        title: Listado de Comunidades
        max_per_page: 10
        display: [ nombre, nombreabrev]
      filter:  ~
      form:    ~
      edit:
        title: 'Edición de la Comunidad: %%NOMBRE%%'
        fields:
          codigocomunidad: {label: Código*, help: 'Código oficial de la comunidad'}
      new:
        title: Nueva Comunidad
        fields:
          codigocomunidad: {label: Código*, help: 'Código oficial de la comunidad'}

