<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../../../../plugins/edaGuardPlugin/lib/servicios/Servicio.class.php';

/**
 * Test class for Servicio.
 * Generated by PHPUnit on 2011-03-11 at 12:37:36.
 */
class ServicioTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Servicio
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Servicio;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testMensajeError().
     */
    public function testMensajeError() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testCrearServicioUsuario().
     */
    public function testCrearServicioUsuario() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testCrearServicioAplicaciones().
     */
    public function testCrearServicioAplicaciones() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testCrearServicioEstructuraOrganizativa().
     */
    public function testCrearServicioEstructuraOrganizativa() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
