generator:
  class: sfPropelGenerator
  param:
    model_class:           EdaCredenciales
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              EdaCredenciales
    plural:                EdaCredencialess
    route_prefix:          eda_credenciales
    with_propel_route:     1
    actions_base_class:    sfActions
    css:                   none

    config:
      actions: ~
      fields:
        EdaAplicaciones: { label: Aplicaci贸n}
        id_aplicacion: { label: Aplicaci贸n}
        nombre: { label: Nombre}
        descripcion: { label : Descripci贸n}
      list:
        title: Listado de Credenciales
        max_per_page: 10
        display: [ nombre, descripcion, EdaAplicaciones ]
      filter:
        display: [ id_aplicacion, nombre, descripcion ]
      form:
        display: [ id_aplicacion, nombre, descripcion ]
      edit:
        title: Edici贸n de la Credencial: %%NOMBRE%%
      new:
        title: Nueva Credencial
