<?php


/**
 * This class defines the structure of the 'sft_fid_atributos' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Apr 23 08:11:19 2012
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.sftFedIdentMapperPlugin.lib.model.map
 */
class SftFidAtributoTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.sftFedIdentMapperPlugin.lib.model.map.SftFidAtributoTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('sft_fid_atributos');
		$this->setPhpName('SftFidAtributo');
		$this->setClassname('SftFidAtributo');
		$this->setPackage('plugins.sftFedIdentMapperPlugin.lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, 11, null);
		$this->addColumn('ID_PROVIDER', 'IdProvider', 'VARCHAR', true, 255, null);
		$this->addColumn('ATRIBUTO', 'Atributo', 'VARCHAR', true, 255, null);
		$this->addColumn('VALOR', 'Valor', 'VARCHAR', true, 255, null);
		$this->addColumn('MAPA', 'Mapa', 'VARCHAR', false, 255, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('SftFidAtributoPerfil', 'SftFidAtributoPerfil', RelationMap::ONE_TO_MANY, array('id' => 'id_atributo', ), 'CASCADE', 'CASCADE');
    $this->addRelation('SftFidAtributoAmbito', 'SftFidAtributoAmbito', RelationMap::ONE_TO_MANY, array('id' => 'id_atributo', ), 'CASCADE', 'CASCADE');
    $this->addRelation('SftFidAtributoEntidad', 'SftFidAtributoEntidad', RelationMap::ONE_TO_ONE, array('id' => 'id_atributo', ), 'CASCADE', 'CASCADE');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // SftFidAtributoTableMap
