generator:
  class: sfPropelGenerator
  param:
    model_class:           SftPerfil
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              SftPerfil
    plural:                SftPerfils
    route_prefix:          sft_perfil_asociaperfiles
    with_propel_route:     1
    actions_base_class:    sfActions
    css:                   none

    config:
      actions: ~
      fields:
        SftUos: { label: UO }
        id_uo:  { label: UO }
        descripcion: {label: Descripción}
        id_ambitotipo: {label: Tipo de ámbito}
      list:       
        max_per_page: 10
        display: [ SftUos, nombre, descripcion ]
      filter:
        display: [ id_uo, id_ambitotipo]
      form:    ~
      edit:    ~
      new:     ~
