<?php


/**
 * Skeleton subclass for performing query and update operations on the 'eda_culturas' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Jun 24 10:10:57 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.edaGuardPlugin.lib.model
 */
class EdaCulturasPeer extends BaseEdaCulturasPeer {

} // EdaCulturasPeer
