<?php


/**
 * Skeleton subclass for performing query and update operations on the 'eda_control__accesos' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Nov 17 12:24:24 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.edaGuardPlugin.lib.model
 */
class EdaControlAccesosPeer extends BaseEdaControlAccesosPeer {

} // EdaControlAccesosPeer
