<?php
/*
* Copyright 2010 Instituto de Tecnologías Educativas - Ministerio de Educación de España
*
* Licencia con arreglo a la EUPL, Versión 1.1 exclusivamente
* (la «Licencia»);
* Solo podrá usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
* 
* y también en:

* http://ec.europa.eu/idabc/en/document/7774.html
*
* Salvo cuando lo exija la legislación aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye «TAL CUAL»,
* SIN GARANTÍAS NI CONDICIONES DE NINGÚN TIPO, ni expresas
* ni implícitas.
* Véase la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/
?>
<?php


/**
 * Skeleton subclass for performing query and update operations on the 'eda_usuarios' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Fri Feb 26 09:22:00 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.edaGuardPlugin.lib.model
 */
class EdaUsuariosPeer extends BaseEdaUsuariosPeer
{
    public static function retrieveByIdSfUser($sfId, PropelPDO $con = null)
    {       
        if ($con === null)
        {
            $con = Propel::getConnection(EdaUsuariosPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        $criteria = new Criteria(EdaUsuariosPeer::DATABASE_NAME);
        $criteria->add(EdaUsuariosPeer::ID_SFUSER, $sfId);

        $v = EdaUsuariosPeer::doSelect($criteria, $con);

        return !empty($v) > 0 ? $v[0] : null;
    }
} // EdaUsuariosPeer
