<?php
/*
* Copyright 2010 Instituto de Tecnologías Educativas - Ministerio de Educación de España
*
* Licencia con arreglo a la EUPL, Versión 1.1 exclusivamente
* (la «Licencia»);
* Solo podrá usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
* 
* y también en:

* http://ec.europa.eu/idabc/en/document/7774.html
*
* Salvo cuando lo exija la legislación aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye «TAL CUAL»,
* SIN GARANTÍAS NI CONDICIONES DE NINGÚN TIPO, ni expresas
* ni implícitas.
* Véase la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/
?>
<?php


/**
 * Skeleton subclass for representing a row from the 'eda_uos' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Fri Feb 26 09:21:59 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.edaGuardPlugin.lib.model
 */
class EdaUos extends BaseEdaUos
{

    /**
     * Initializes internal state of EdaUos object.
     * @see        parent::__construct()
     */
    public function __construct()
    {
        // Make sure that parent constructor is always invoked, since that
        // is where any default values for this object are set.
        parent::__construct();
    }

    public function getIdUo()
    {
        return $this -> getId();
    }

    public function  __toString()
    {
        if(is_null(self::getNombre()))
        {
            return self::getNombre('es_ES');
        }
        else
        {
            return self::getNombre();
        }
    }

    public function noTienePeriodos()
    {
        if(count($this -> getEdaPeriodoss()) == 0)
            return true;
        else
            return false;
    }

    public function dameNumeroPeriodos()
    {
        return count($this -> getEdaPeriodoss());
    }

    public function noTienePerfiles()
    {
        if(count($this -> getEdaPerfiless()) == 0)
            return true;
        else
            return false;
    }

    public function dameNumeroPerfiles()
    {
        return count($this -> getEdaPerfiless());
    }
} // EdaUos
