<?php


/**
 * Skeleton subclass for representing a row from the 'eda_usu_atributos_valores' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Mar 29 18:09:01 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.edaGuardPlugin.lib.model
 */
class EdaUsuAtributosValores extends BaseEdaUsuAtributosValores {

        /**
	 * Get the name of the user.
	 *
	 * @return     string
	 */
	public function getNombreUsuario()
	{
            if ($this->aEdaUsuarios === null && ($this->id_usuario !== null)) {
    
        	return $this->getEdaUsuarios()->NombreCompleto();
            }else return '';
	}

} // EdaUsuAtributosValores
