<?php


/**
 * Skeleton subclass for representing a row from the 'eda_usu_atributos' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Mar 29 18:09:01 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.edaGuardPlugin.lib.model
 */
class EdaUsuAtributos extends BaseEdaUsuAtributos
{
    public function  __toString()
    {
        return $this -> getNombre();
    }
} // EdaUsuAtributos
