generator:
  class: sfPropelGenerator
  param:
    model_class:           EdaAmbitos
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              EdaAmbitos
    plural:                EdaAmbitoss
    route_prefix:          eda_ambitos
    with_propel_route:     1
    actions_base_class:    sfActions
    css:                   none

    config:
      actions: ~
      fields:
        id_periodo: { label: Periodos }
        EdaPeriodos: { label: Periodos }
        id_ambitotipo: { label: Tipos de Ámbitos}
      list:
        title: Listado de Ámbitos
        max_per_page: 10
        display: [ nombre, descripcion, EdaPeriodos, estado ]         
      filter:  ~
      form:    ~
      edit:
        title: Edición del Ámbito <i>%%NOMBRE%%</i>  del tipo de ámbito <i>%%EDAAMBITOSTIPOS%%</i>
      new:
        title: Nuevo Ámbito para el tipo <i>%%EDAAMBITOSTIPOS%%</i>
