generator:
  class: sfPropelGenerator
  param:
    model_class:           SftPerfil
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              SftPerfil
    plural:                SftPerfils
    route_prefix:          sft_perfil
    with_propel_route:     1
    actions_base_class:    sfActions
    css:                   none

    config:
      actions: ~
      fields:
        id_uo:           { label: UO }
        id_ambitotipo:   { label: Tipo Ámbito }
        SftUo:          { label: UO }
        SftAmbitoTipo: { label: Tipo Ámbito }
        created_at:      { label: Creado }
        updated_at:      { label: Actualizado }
        
      list:
        title: Listado de Perfiles
        max_per_page: 10
        display: [ nombre, SftUo, SftAmbitoTipo]
        object_actions:
          _edit: ~
          _delete: ~
          asociaCredenciales: { label: Gest. Credenciales }
          verCredeciales:     { label: Ver Credenciales }
      filter:
        display: [ id_uo, id_ambitotipo ]
      form:    ~
      edit:
        title: 'Edición del Perfil: %%NOMBRE%%'
        fields:
          codigo: {label: Código*, help: 'Nombre corto del periodo, va en minúsculas y sin espacios ni símbolos extraños y se suele utilizar para identificarlo'}
          menu: { label: Menú, help: 'Dejar en blanco si se utiliza el constructor de menú de symfonite' }

      new:
        title: Nuevo Perfil
        fields:
          codigo: {label: Código*, help: 'Nombre corto del periodo, va en minúsculas y sin espacios ni símbolos extraños y se suele utilizar para identificarlo'}
          menu: { label: Menú, help: 'Dejar en blanco si se utiliza el constructor de menú de symfonite' }

