generator:
  class: sfPropelGenerator
  param:
    model_class:           SftPerfil
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              SftPerfil
    plural:                SftPerfils
    route_prefix:          sft_perfil
    with_propel_route:     1
    actions_base_class:    sfActions
    css:                   none

    config:
      actions: ~
      fields:
        id_uo:           { label: UO }
        id_ambitotipo:   { label: Tipo Ámbito }
        SftUos:          { label: UO }
        SftAmbitosTipos: { label: Tipo Ámbito }
        created_at:      { label: Creado }
        updated_at:      { label: Actualizado }
        
      list:
        title: Listado de Perfiles
        max_per_page: 10
        display: [ nombre, SftUo, SftAmbitoTipo]
        object_actions:
          _edit: ~
          _delete: ~
          asociaCredenciales: { label: Gest. Credenciales }
          verCredeciales:     { label: Ver Credenciales }
      filter:
        display: [ id_uo, id_ambitotipo ]
      form:    ~
      edit:
        title: Edición del Perfil: %%NOMBRE%%
      new:
        title: Nuevo Perfil
