generator:
  class: sfPropelGenerator
  param:
    model_class:           EdaOrganismos
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              EdaOrganismos
    plural:                EdaOrganismoss
    route_prefix:          eda_organismos
    with_propel_route:     1
    actions_base_class:    sfActions
    css:                   none

    config:
      actions:
        _new:    { credentials: [EDAGESTIONPLUGIN_administracion] }
      fields:
        docidentificacion: { label: Documento }
        id_tipodocidentificacion: {label: Tipo Documento }
        id_paisdocidentificacion: {label: País del Documento }
        sfusername: { label: Username }
      list:
        title: Listado de Organismos
        display: [ =nombre, abreviatura, sfusername, sitioweb]
        max_per_page: 10
        object_actions:
          _edit: ~
          _delete: ~
          asociaPerfiles: { label: perfiles }

      filter:
        display: [ nombre, abreviatura, sitioweb]
      form:
        class: EdaOrganismosConTelEmailDirForm
      edit:
        title: Edición del Organismo: %%NOMBRE%% (%%ABREVIATURA%%)
      new:
        title: Nuevo Organismo
