generator:
  class: sfPropelGenerator
  param:
    model_class:           EdaUsuAtributosValores
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              EdaUsuAtributosValores
    plural:                EdaUsuAtributosValoress
    route_prefix:          eda_usu_atributos_valores_asociaatributos
    with_propel_route:     1
    actions_base_class:    sfActions
    css:                 none

    config:
      actions: ~
      fields:
        id_usuario: { label: Usuario }
        id_usu_atributo: { label: Atributo }
        EdaUsuAtributos: { label: Nombre }
        valor: { label: Valor }
        created_at: { label: Fecha de Creación }
        updated_at: { label: Ultima actualización }
        expira: { label: Expira}
      list:
        title: Listado de Atributos del usuario
        max_per_page: 10
        object_actions:
          _edit: ~
          _delete: ~
        display: [ EdaUsuAtributos, valor, created_at, updated_at, expira ]
      filter:
        display: [ id_usuario, id_usu_atributo ]
      form:    ~
      edit:
        title: Edición del Atributo %%EdaUsuAtributos%%
      new:
        title: Crear un nuevo atributo