page: Inicio
module: inicio
action: index
credential: EDAGESTIONPLUGIN_administracion
menu:
  -
     page: UOS
     module: uos
     action: index
     credential: EDAGESTIONPLUGIN_administracion
     menu:
       -
         page: gestión de uos
         module: uos
         action: index
         credential: EDAGESTIONPLUGIN_administracion
       -
         page: gestión de periodos
         module: periodos
         action: index
         credential: EDAGESTIONPLUGIN_administracion
       -
         page: gestión de perfiles
         module: perfiles
         action: index
         credential: EDAGESTIONPLUGIN_administracion
       -
         page: gestión de ámbitos
         module: ambitostipos
         action: index
         credential: EDAGESTIONPLUGIN_administracion
  -
     page: Aplicaciones
     module: aplicaciones
     action: index
     credential: EDAGESTIONPLUGIN_administracion
     menu:
       -
         page: gestión de aplicaciones
         module: aplicaciones
         action: index
         credential: EDAGESTIONPLUGIN_administracion
       -
         page: gestión de credenciales
         module: credenciales
         action: index
         credential: EDAGESTIONPLUGIN_administracion
       -
         page: gestión de culturas
         module: culturas
         action: index
         credential: EDAGESTIONPLUGIN_administracion
  -
     page: Usuarios
     module: personas
     action: index
     credential: EDAGESTIONPLUGIN_administracion
     menu:
       -
         page: gestión de personas
         module: personas
         action: index
         credential: EDAGESTIONPLUGIN_administracion_uo
       -
         page: gestión de organismos
         module: organismos
         action: index
         credential: EDAGESTIONPLUGIN_administracion_uo       
  -
     page: Localizaciones
     module: paises
     action: index
     credential: EDAGESTIONPLUGIN_administracion
     menu:
       -
         page: gestión países
         module: paises
         action: index
         credential: EDAGESTIONPLUGIN_administracion
       -
         page: gestión de comunidades
         module: comunidades
         action: index
         credential: EDAGESTIONPLUGIN_administracion
       -
         page: gestión de provincias
         module: provincias
         action: index
         credential: EDAGESTIONPLUGIN_administracion
  -
     page: Datos Auxiliares
     module: tiposdoc
     action: index
     credential: EDAGESTIONPLUGIN_administracion
     menu:
       -
         page: gestión de tipos de documentos
         module: tiposdoc
         action: index
         credential: EDAGESTIONPLUGIN_administracion
       -
         page: gestión de tipos de direcciones
         module: tiposdir
         action: tiposdir/index
         credential: EDAGESTIONPLUGIN_administracion
       -
         page: gestión de tipos de organismos
         module: tiposorg
         action: index
         credential: EDAGESTIONPLUGIN_administracion
       -
         page: gestión de tipos de telefonos
         module: tipostel
         action: index
         credential: EDAGESTIONPLUGIN_administracion
  -
     page: Identificaciones
     module: sfGuardUser
     action: index
     credential: EDAGESTIONPLUGIN_administracion
     menu:
       -
         page: gestión de identificaciones
         module: sfGuardUser
         action: index
         credential: EDAGESTIONPLUGIN_administracion
       -
         page: gestión de grupos
         module: sfGuardGroup
         action: index
         credential: EDAGESTIONPLUGIN_administracion
       -
         page: gestión de permisos
         module: sfGuardPermission
         action: index
         credential: EDAGESTIONPLUGIN_administracion
       -
         page: gestión de atributos
         module: atributos
         action: index
         credential: EDAGESTIONPLUGIN_administracion_uo
  -
     page: Menus
     module: sfBreadNavAdmin
     action: index
     credential: EDAGESTIONPLUGIN_administracion
     menu:
       -
         page: gestión de menús
         module: sfBreadNavAdmin
         action: index
         credential: EDAGESTIONPLUGIN_administracion
       -
         page: listado de menús
         module: sfBreadNavAdmin
         action: list
         credential: EDAGESTIONPLUGIN_administracion