generator:
  class: sfPropelGenerator
  param:
    model_class:           SftDireccion
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              SftDireccion
    plural:                SftDireccions
    route_prefix:          sft_direccion
    with_propel_route:     1
    actions_base_class:    sfActions
    css:                   false

    config:
      actions: ~
      fields:
        tipovia: {label: Tipo de vía}
        numero: {label: Número}
        pais: {label: País}
        id_tipodireccion: {label: Tipo de dirección}
      list:    
        title: Listado de direcciones
        max_per_page: 10 
        display: [ domicilio, numero, escalera, piso, letra, municipio, provincia, pais ]
      filter:  
        class: DireccionIdUsuarioHiddenFormFilter
      form:    
        class: DireccionIdUsuarioHiddenForm
      edit:    
        title: Edicion de la direccion
        fields:
          id_tipodireccion: {label: Tipo de dirección*, help: 'Define el tipo de dirección (casa, trabajo, ...)'}
      new:     
        title: Nueva direccion
        fields:
          id_tipodireccion: {label: Tipo de dirección*, help: 'Define el tipo de dirección (casa, trabajo, ...)'}
