<?php

/**
 * Skeleton subclass for representing a row from the 'sft_fid_atributos' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Dec 12 09:11:29 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.sftFedIdentMapperPlugin.lib.model
 */
class SftFidAtributo extends BaseSftFidAtributo
{
    public function ponPerfil($id_perfil)
    {
        $ap = new SftFidAtributoPerfil();
        $ap->setIdAtributo($this->getId());
        $ap->setIdPerfil($id_perfil);
        $ap->save();
    }
    
    public function quitaPerfil($id_perfil)
    {
        $ap = SftFidAtributoPerfilPeer::retrieveByPK($this->getId(), $id_perfil);
        $ap->delete();
    }
    
     public function ponAmbito($id_ambito)
    {
        $aa = new SftFidAtributoAmbito();
        $aa->setIdAtributo($this->getId());
        $aa->setIdAmbito($id_ambito);
        $aa->save();
    }
    
    public function quitaAmbito($id_ambito)
    {
        $aa = SftFidAtributoAmbitoPeer::retrieveByPK($this->getId(), $id_ambito);
        $aa->delete();
    }
}

// SftFidAtributo
