<?php


/**
 * Skeleton subclass for performing query and update operations on the 'sft_fid_atributo_actualizable' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Dec 12 09:11:29 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.sftFedIdentMapperPlugin.lib.model
 */
class SftFidAtributoEntidadPeer extends BaseSftFidAtributoEntidadPeer {

} // SftFidAtributoEntidadPeer
