generator:
  class: sfPropelGenerator
  param:
    model_class:           SftCredencial
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              SftCredencial
    plural:                SftCredencials
    route_prefix:          sft_credencial
    with_propel_route:     1
    actions_base_class:    sfActions
    css:                   none

    config:
      actions: ~
      fields:
        SftAplicaciones: { label: Aplicaci贸n}
        id_aplicacion: { label: Aplicaci贸n}
        nombre: { label: Nombre}
        descripcion: { label : Descripci贸n}
      list:
        title: Listado de Credenciales
        max_per_page: 10
        display: [ nombre, descripcion ]
      filter:
        class: credencialFormFilter
        display: [ id_aplicacion, nombre, descripcion ]
      form:
        class: credencialForm
        display: [ id_aplicacion, nombre, descripcion ]
      edit:
        title: Edici贸n de la Credencial
      new:
        title: Nueva Credencial
