<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../../../../plugins/sftGuardPlugin/lib/util/Utilidades.class.php';

/**
 * Test class for Utilidades.
 * Generated by PHPUnit on 2011-03-11 at 12:38:06.
 */
class UtilidadesTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Utilidades
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Utilidades;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testGeneraClave().
     */
    public function testGeneraClave() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testLimpiarCadena().
     */
    public function testLimpiarCadena() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testDameUsuarioConSesionActiva().
     */
    public function testDameUsuarioConSesionActiva() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testIsSfBreadNavMenu().
     */
    public function testIsSfBreadNavMenu() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetNumDaysInBetween().
     */
    public function testGetNumDaysInBetween() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
