generator:
  class: sfPropelGenerator
  param:
    model_class:           EdaCredenciales
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              EdaCredenciales
    plural:                EdaCredencialess
    route_prefix:          eda_credenciales_asociacredenciales
    with_propel_route:     1
    actions_base_class:    sfActions
    css:                   none

    config:
      actions: ~
      fields:
        id_aplicacion: { label: Aplicación }
        EdaAplicaciones: { label: Aplicación }
        nombre: { label: Nombre }
        descripcion: { label: Descripción }
        eda_perfil_credencial_list: { label: perfiles }
      
      list:
        max_per_page: 10
        display: [ EdaAplicaciones, nombre, descripcion ]
      filter:  ~

      form:    ~
      edit:    ~
      new:     ~
