<?php

/**
 * Skeleton subclass for performing query and update operations on the 'sft_aplicaciones' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sun Oct 23 16:15:17 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.sftGuardPlugin.lib.model
 */
class SftAplicacionPeer extends BaseSftAplicacionPeer
{

    static public function dameAplicacionConClave($clave)
    {
        $c = new Criteria();
        $c->add(SftAplicacionPeer::CLAVE, $clave);

        $aplicacion = SftAplicacionPeer::doSelectOne($c);

        return $aplicacion;
    }

}

// SftAplicacionPeer
