<?php


/**
 * Skeleton subclass for representing a row from the 'sft_accesos' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sun Oct 23 10:50:44 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.sftGuardPlugin.lib.model
 */
class SftAcceso extends BaseSftAcceso {
/**
     * Initializes internal state of SftAcceso object.
     * @see        parent::__construct()
     */
    public function __construct()
    {
        // Make sure that parent constructor is always invoked, since that
        // is where any default values for this object are set.
        parent::__construct();
    }

    public function getIdAcceso()
    {
        return $this -> getId();
    }

    public function __toString()
    {
        $alias  = self::getSftUsuario()->getAlias();
        $perfil = self::getSftPerfil()->getDescripcion();
        $uo     = self::getSftPerfil()->getSftUo()->getCodigo();
        return $alias.":".$perfil.":".$uo;
    }


    /**
     * Devuelve los ámbitos activos de un acceso en un ejercicio académico dado.
     * Si el perfil del acceso no tiene ámbitos (id_ambito = NULL) en la tabla
     * 'sft_tiposambito' devuelve NULL
     *
     * @param unknown_type $id_ea
     */
    public function dameAmbitos($id_ea)
    {
        $id_ambito = self::getSftPerfil()->getIdAmbito();

        if(!$id_ambito) // Perfil sin ámbitos

        {
            return null;
        }
        else //Buscamos los ámbitos activos en el ejercicio académico dado

        {
            $oAmbito       = SftAmbitoPeer::retrieveByPK($id_ambito);
            $aTablaAmbito  = $oAmbito -> getTabla();
            $aClasePeer    = sfInflector::camelize($aTablaAmbito).'Peer';

            $aTablaAccesosAmbito = "sft_accesos_".$aTablaAmbito;

            $con = Propel::getConnection();
            $sql = "select aa.id_ambito from $aTablaAccesosAmbito aa, $aTablaAmbito a where aa.id_acceso=".self::getIdAcceso()." and aa.id_ambito=a.id_ambito and a.id_ejercicioacademico=".$id_ea;
            $stn = $con -> prepareStatement($sql);
            $rs  = $stn -> executeQuery();

            $tAmbitos = array();
            while($rs->next())
            {
                $id = $rs -> getInt('id_ambito'); //Este id es el id_ambito de la tabla de ambitos en cuestion

                $tAmbitos[] = call_user_func(array($aClasePeer,"retrieveByPK"),$id);

                //			MenAulasPeer::retrieveByPK($id);

            }
            return $tAmbitos;
        }

    }

    /**
     * Devuelve el objeto Ambito con id_ambito=$id_ambito
     *
     * @param unknown_type $id_ambito
     */
    public function dameAmbito($id)
    {
        if(is_null($id))
        {
            echo "Parámetro incorrecto";
            exit;
        }
        $id_ambito = self::getSftPerfil()->getIdAmbito();

        $oAmbito       = SftAmbitoPeer::retrieveByPK($id_ambito);
        $aTablaAmbito  = $oAmbito -> getTabla();
        $aClasePeer    = sfInflector::camelize($aTablaAmbito).'Peer';

        $aTablaAccesosAmbito = "sft_accesos_".$aTablaAmbito;

        $con = Propel::getConnection();
        $sql = "select id_ambito from $aTablaAmbito where id_ambito=".$id;
        $stn = $con -> prepareStatement($sql);
        $rs  = $stn -> executeQuery();
        $rs->next();
        $id = $rs -> getInt('id_ambito'); //Este id es el id_ambito de la tabla de ambitos en cuestion

        $Ambito = call_user_func(array($aClasePeer,"retrieveByPK"),$id);

        return $Ambito;

    }

    public function ponAmbito($ambito)
    {        
        $accesos_ambitos = new SftAccesoAmbito();

        $accesos_ambitos -> setSftAmbito($ambito);
        $accesos_ambitos -> setSftAcceso($this);
        $accesos_ambitos -> save();

    }

    public function quitaAmbito($ambito)
    {
        $c = new Criteria();

        $c -> add(SftAccesoAmbitoPeer::ID_AMBITO, $ambito -> getId());
        $c -> add(SftAccesoAmbitoPeer::ID_ACCESO, $this -> getId());

        $acceso_ambito = SftAccesoAmbitoPeer::doSelectOne($c);
        $acceso_ambito -> delete();

    }

    public function tieneAmbito($ambito)
    {
        $c = new Criteria();

        $c -> add(SftAccesoAmbitoPeer::ID_AMBITO, $ambito -> getId());
        $c -> addJoin(SftAccesoAmbitoPeer::ID_ACCESO, SftAccesoPeer::ID);
        $c -> add(SftAccesoPeer::ID, $this -> getId());

        $accesos_ambitos = SftAccesoAmbitoPeer::doSelect($c);

        if(count($accesos_ambitos) > 0)
        {
            return true;
        }
        else
        {
            return false;
        }
    }

} // SftAcceso
