<?php


/**
 * Skeleton subclass for representing a row from the 'sft_perfil_credencial' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sun Oct 23 10:50:50 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.sftGuardPlugin.lib.model
 */
class SftPerfilCredencial extends BaseSftPerfilCredencial {

} // SftPerfilCredencial
