<?php


/**
 * Skeleton subclass for performing query and update operations on the 'sft_tipostelefono_i18n' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Oct 24 08:53:03 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.sftGuardPlugin.lib.model
 */
class SftTipoTelefonoI18nPeer extends BaseSftTipoTelefonoI18nPeer {

} // SftTipoTelefonoI18nPeer
