<?php


/**
 * Skeleton subclass for performing query and update operations on the 'sft_uos_i18n' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Nov 14 08:40:51 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.sftGuardPlugin.lib.model
 */
class SftUoI18nPeer extends BaseSftUoI18nPeer {

} // SftUoI18nPeer
