<?php


/**
 * Skeleton subclass for performing query and update operations on the 'sft_usu_atributos' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sun Oct 23 16:15:27 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.sftGuardPlugin.lib.model
 */
class SftUsuAtributoPeer extends BaseSftUsuAtributoPeer {

} // SftUsuAtributoPeer
