<?php

/**
 * Skeleton subclass for performing query and update operations on the 'sft_usuarios' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sun Oct 23 16:15:26 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.sftGuardPlugin.lib.model
 */
class SftUsuarioPeer extends BaseSftUsuarioPeer
{

    public static function retrieveByIdSfUser($sfId, PropelPDO $con = null)
    {
        if ($con === null)
        {
            $con = Propel::getConnection(SftUsuarioPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        $criteria = new Criteria(SftUsuarioPeer::DATABASE_NAME);
        $criteria->add(SftUsuarioPeer::ID_SFUSER, $sfId);

        $v = SftUsuarioPeer::doSelect($criteria, $con);

        return!empty($v) > 0 ? $v[0] : null;
    }

}

// SftUsuarioPeer
