<?php

/**
 * Skeleton subclass for representing a row from the 'sft_uos' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sun Oct 23 16:15:26 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.sftGuardPlugin.lib.model
 */
class SftUo extends BaseSftUo
{

    /**
     * Initializes internal state of SftUo object.
     * @see        parent::__construct()
     */
    public function __construct()
    {
        // Make sure that parent constructor is always invoked, since that
        // is where any default values for this object are set.
        parent::__construct();
    }

    public function getIdUo()
    {
        return $this->getId();
    }

    public function __toString()
    {
        if (is_null(self::getNombre()))
        {
            return self::getNombre('es_ES');
        } else
        {
            return self::getNombre();
        }
    }

    public function noTienePeriodos()
    {
        if (count($this->getSftPeriodos()) == 0)
            return true;
        else
            return false;
    }

    public function dameNumeroPeriodos()
    {
        return count($this->getSftPeriodos());
    }

    public function noTienePerfiles()
    {
        if (count($this->getSftPerfils()) == 0)
            return true;
        else
            return false;
    }

    public function dameNumeroPerfiles()
    {
        return count($this->getSftPerfils());
    }

}

// SftUo
