generator:
  class: sfPropelGenerator
  param:
    model_class:           EdaPerfiles
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              EdaPerfiles
    plural:                EdaPerfiless
    route_prefix:          eda_perfiles_asociaperfiles
    with_propel_route:     1
    actions_base_class:    sfActions
    css:                   none

    config:
      actions: ~
      fields:
        EdaUos: { label: UO }
        id_uo:  { label: UO }
      list:       
        max_per_page: 10
        display: [ EdaUos, nombre, descripcion ]
      filter:
        display: [ id_uo, id_ambitotipo, menu]
      form:    ~
      edit:    ~
      new:     ~
