generator:
  class: sfPropelGenerator
  param:
    model_class:           EdaTiposDireccion
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              EdaTiposDireccion
    plural:                EdaTiposDireccions
    route_prefix:          eda_tipos_direccion
    with_propel_route:     1
    actions_base_class:    sfActions
    css:                   none

    config:
      actions: ~
      fields:
        created_at: { label: Creado }
        updated_at: { label: Actualizado }        
      list:
        title: Listado de Tipos de Direcciones
        max_per_page: 10
        display: [ nombre ]
      filter:  ~
      form:    ~
      edit:
        title: Edición del Tipo de Dirección: %%NOMBRE%%
      new:
        title: Nuevo Tipo de Dirección
