<?php


/**
 * This class defines the structure of the 'sf_BreadNav' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Jun 24 13:39:27 2011
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.sfBreadNav2Plugin.lib.model.map
 */
class sfBreadNavTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.sfBreadNav2Plugin.lib.model.map.sfBreadNavTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('sf_BreadNav');
		$this->setPhpName('sfBreadNav');
		$this->setClassname('sfBreadNav');
		$this->setPackage('plugins.sfBreadNav2Plugin.lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('PAGE', 'Page', 'VARCHAR', true, 255, null);
		$this->addColumn('TITLE', 'Title', 'VARCHAR', true, 255, null);
		$this->addColumn('MODULE', 'Module', 'VARCHAR', true, 128, null);
		$this->addColumn('ACTION', 'Action', 'VARCHAR', true, 128, null);
		$this->addColumn('CREDENTIAL', 'Credential', 'VARCHAR', false, 128, null);
		$this->addColumn('CATCHALL', 'Catchall', 'BOOLEAN', false, null, null);
		$this->addColumn('TREE_LEFT', 'TreeLeft', 'INTEGER', true, null, null);
		$this->addColumn('TREE_RIGHT', 'TreeRight', 'INTEGER', true, null, null);
		$this->addColumn('TREE_PARENT', 'TreeParent', 'INTEGER', true, null, null);
		$this->addForeignKey('SCOPE', 'Scope', 'INTEGER', 'sf_BreadNav_Application', 'ID', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('sfBreadNavApplication', 'sfBreadNavApplication', RelationMap::MANY_TO_ONE, array('scope' => 'id', ), 'CASCADE', null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // sfBreadNavTableMap
