<?php


/**
 * This class defines the structure of the 'sf_BreadNav_Application' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Apr 18 17:38:20 2012
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.sfBreadNav2Plugin.lib.model.map
 */
class sfBreadNavApplicationTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.sfBreadNav2Plugin.lib.model.map.sfBreadNavApplicationTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('sf_BreadNav_Application');
		$this->setPhpName('sfBreadNavApplication');
		$this->setClassname('sfBreadNavApplication');
		$this->setPackage('plugins.sfBreadNav2Plugin.lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('USER_ID', 'UserId', 'INTEGER', false, null, null);
		$this->addColumn('NAME', 'Name', 'VARCHAR', true, 255, null);
		$this->addColumn('APPLICATION', 'Application', 'VARCHAR', true, 255, null);
		$this->addColumn('CSS', 'Css', 'VARCHAR', true, 2000, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('sfBreadNav', 'sfBreadNav', RelationMap::ONE_TO_MANY, array('id' => 'scope', ), 'CASCADE', null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // sfBreadNavApplicationTableMap
