rgtsugerencia:
  class: sfPropelRouteCollection
  options:
    model:                rgtsugerencia
    module:               sugerencias_admin
    prefix_path:          /sugerencias_admin
    column:               id
    with_wildcard_routes: true



registro:
  url: /registro
  param: { module: registro, action: index }
  
registro_enviarTokenRegistro:
  url:   /registro/enviarTokenRegistro
  param: { module: registro, action: enviarTokenRegistro }
  
registro_confirmaRegistro:
  url:   /registro/confirmaRegistro
  param: { module: registro, action: confirmaRegistro }
  
registro_mensajeEnviado:
  url:   /registro/mensajeEnviado
  param: { module: registro, action: mensajeEnviado }
  
sugerencias:
  url: /sugerencias
  param: { module: sugerencias, action: index }
