generator:
  class: sfPropelGenerator
  param:
    model_class:           GenPaises
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              GenPaises
    plural:                GenPaisess
    route_prefix:          gen_paises
    with_propel_route:     1
    actions_base_class:    sfActions
    css:                   none

    config:
      actions: ~
      fields:  ~
      list:
        title: Listado de Países
        max_per_page: 10
        display: [ nombre, codigo_iso3166_alfa2, codigo_iso3166_alfa3, codigo_iso3166_num ]
      filter:
        display: [ codigo_iso3166_alfa2, codigo_iso3166_alfa3, codigo_iso3166_num ]
      form:    ~
      edit:
        title: Edición del País: %%NOMBRE%%
      new:
        title: Nuevo País
